### ISSUE TITLE
About Capital City of Jakarta

### ISSUE THREAD

**Issue by andiyan1** [asbasawaraj/Indonesia#2]
<img width="482" alt="screen shot 2018-04-25 at 16 03 47" src="https://user-images.githubusercontent.com/7466361/39236190-53a64816-48a2-11e8-9af6-1497635b50c8.png">
Jakarta is a capital city of 20 million people and rising, separated into 5 districts and 5 administrative city..

**Comment by asbasawaraj** [comment]
I have added the details
